### ISSUE TITLE
NetSuite Integration Custom Fields

### ISSUE THREAD

**Issue by SEAnderson07** [wombat/netsuite_integration#28]
Within my NetSuite, I have a custom customer field called "custentity_cutomer_uuid" added by NetSuite support. I have been reviewing the NetSuite integration and see that the customer service class has a "handle_extra_fields". Is there documentation anywhere or a recommended way to use this handle_extra_field function or some other method to pass a custom field and its value via the NetSuite integration? Thanks!

**Comment by huoxito** [comment]
hi @SEAnderson07 actually our integration won't send any fields that are not defined on the underlying [netsuite library](https://github.com/NetSweet/netsuite). Unless there's an attribute defined [here](https://github.com/NetSweet/netsuite/blob/2e2be1b9e224afd4e0795dabc1220577e151761a/lib/netsuite/records/customer.rb#L14) it won't work in our integration.

So only way I can think of to make this work is forking that gem to add your custom field and also forking our integration so you can point to your netsuite fork .. perhaps would be easier to double check with NS support if you can use one of the built in fields (every NS object has about a hundred fields iirc maybe you could use one of them instead)

**Comment by SEAnderson07** [comment]
Thank you @huoxito. Your answer is very helpful. I will try your suggestions and see which one works the best for my particular project.
